@echo off

SETLOCAL ENABLEDELAYEDEXPANSION

rem SET /P remote=Enter Remote URL:

cd %cd%

rem Create .gitignore file
echo /[Ll]ibrary/>.gitignore
echo /[Tt]emp/>>.gitignore
echo /[Oo]bj/>>.gitignore
echo /[Bb]uild/>>.gitignore
echo /[Bb]uilds/>>.gitignore
echo /Assets/AssetStoreTools*>>.gitignore
echo.>>.gitignore
echo # Visual Studio 2015 cache directory>>.gitignore
echo /.vs/>>.gitignore
echo.>>.gitignore
echo # Autogenerated VS/MD/Consulo solution and project files>>.gitignore
echo ExportedObj/>>.gitignore
echo .consulo/>>.gitignore
echo *.csproj>>.gitignore
echo *.unityproj>>.gitignore
echo *.sln>>.gitignore
echo *.suo>>.gitignore
echo *.tmp>>.gitignore
echo *.user>>.gitignore
echo *.userprefs>>.gitignore
echo *.pidb>>.gitignore
echo *.booproj>>.gitignore
echo *.svd>>.gitignore
echo *.pdb>>.gitignore
echo.>>.gitignore
echo # Unity3D generated meta files>>.gitignore
echo *.pidb.meta>>.gitignore
echo.>>.gitignore
echo # Unity3D Generated File On Crash Reports>>.gitignore
echo sysinfo.txt>>.gitignore
echo.>>.gitignore
echo # Builds>>.gitignore
echo *.apk>>.gitignore
echo *.unitypackage>>.gitignore


git lfs install
git init
git lfs track "*.psd"
git lfs track "*.png"
git lfs track "*.mp3"
git lfs track "*.wav"
git lfs track "*.prefab"
git lfs track "*.fbx"
git lfs track "*.xcf"

rem git remote add origin remote

git add .

git commit -m "Unity Git Init"
git remote add origin https://github.com/SimonSkov222/Project-X.git
git push -u origin master




pause